/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e5e2e2",
        "primary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#201b0c",
        "primary-container": "#c5a059",
        "on-primary-fixed": "#261900",
        "tertiary-container": "#ada58e",
        "inverse-surface": "#303031",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        secondary: "#5f5e5e",
        "on-surface": "#1b1b1c",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdea5",
        "on-tertiary": "#ffffff",
        "authentic-emerald": "#2D4B3F",
        "tertiary-fixed": "#ece2c9",
        "surface-tint": "#775a19",
        "outline-variant": "#d1c5b4",
        "tertiary-fixed-dim": "#cfc6ae",
        primary: "#775a19",
        "on-primary-fixed-variant": "#5d4201",
        "surface-container-highest": "#e5e2e2",
        "surface-container-high": "#eae7e7",
        surface: "#fcf9f9",
        "on-background": "#1b1b1c",
        tertiary: "#655e4b",
        "on-error-container": "#93000a",
        outline: "#7f7667",
        "on-tertiary-container": "#403b29",
        charcoal: "#1A1A1A",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f3",
        background: "#fcf9f9",
        "antique-gold": "#D7C8BB",
        "inverse-on-surface": "#f3f0f0",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1b1c1c",
        "secondary-container": "#e4e2e1",
        "silver-gray": "#94908D",
        "on-primary-container": "#4e3700",
        "on-surface-variant": "#4e4639",
        "surface-container": "#f0eded",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#474746",
        "secondary-fixed": "#e4e2e1",
        "on-secondary-container": "#656464",
        "surface-bright": "#fcf9f9",
        "surface-dim": "#dcd9d9",
        "on-tertiary-fixed-variant": "#4c4634",
        "inverse-primary": "#e9c176",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        base: "8px",
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "title-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "data-mono": ["Inter"],
      },
      fontSize: {
        "label-caps": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.1em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "44px", fontWeight: "600" },
        ],
        "title-lg": [
          "20px",
          {
            lineHeight: "28px",
            letterSpacing: "0.01em",
            fontWeight: "600",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": [
          "32px",
          { lineHeight: "40px", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "32px", fontWeight: "500" },
        ],
        "data-mono": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
}
